/**
 * 配置页视图提供者 (Config Page View Provider)
 *
 * 在首次启动时或用户手动打开时显示配置页，引导用户填写 LLM API 密钥等必要配置，
 * 避免让用户去 Settings 页面编写 JSON 配置。
 *
 * **重要**: 配置现在保存在工作区的 .env 文件中，而不是 VSCode 设置中。
 *
 * 关联文件：
 * - @extension/src/extension.ts - 主入口，注册命令 'aiSocialScientist.openConfigPage'
 * - @extension/src/envManager.ts - .env文件读写管理
 * - @extension/src/services/llmValidator.ts - LLM配置验证服务
 * - @extension/src/services/backendManager.ts - 后端服务管理（配置保存后启动）
 * - @extension/src/webview/configPage/ - 前端React组件 (编译后为configPage.js)
 *
 * 后端API：
 * - @packages/agentsociety2/agentsociety2/backend/app.py - FastAPI后端
 */

import * as vscode from 'vscode';
import * as path from 'path';
import * as fs from 'fs';
import { localize } from './i18n';
import type { ConfigValues, WorkspaceInfo } from './webview/configPage/types';
import { EnvManager, EnvConfig } from './envManager';
import { LLMValidator, PythonValidator, LLMType } from './services/llmValidator';

/** Build EasyPaper agents YAML content from AgentSociety2 config (LLM/VLM). API Base uses llmApiBase. */
function buildEasyPaperYaml(config: Partial<EnvConfig>): string {
  const llmKey = (config.easypaperLlmApiKey ?? '').trim() || (config.llmApiKey ?? '').trim();
  const llmBase = (config.llmApiBase ?? 'https://cloud.infini-ai.com/maas/v1').trim();
  const llmModel = (config.easypaperLlmModel ?? '').trim() || (config.llmModel ?? 'qwen3-next-80b-a3b-instruct').trim();
  const vlmModel = (config.easypaperVlmModel ?? '').trim() || 'qwen3-vl-235b-a22b-thinking';
  const vlmKey = (config.easypaperVlmApiKey ?? '').trim() || llmKey;
  const vlmBase = llmBase;
  const esc = (s: string) => (s.includes(':') || s.includes('"') || s.includes('\n') ? `"${String(s).replace(/"/g, '\\"')}"` : s);
  const lines: string[] = [
    '# Generated by AgentSociety2. Use with EasyPaper: AGENT_CONFIG_PATH=<path-to-this-file>',
    'agents:',
    '  - name: paper_parser',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: template_parser',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: commander',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: writer',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '    writer_config:',
    '      max_review_iterations: 2',
    '      enable_review: true',
    '      enable_tools: true',
    '      available_tools:',
    '        - validate_citations',
    '        - count_words',
    '        - check_key_points',
    '  - name: typesetter',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: metadata',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '    metadata_config:',
    '      enable_mini_review: true',
    '      max_review_iterations: 2',
    '  - name: reviewer',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: planner',
    '    model:',
    `      model_name: ${esc(llmModel)}`,
    `      api_key: ${esc(llmKey)}`,
    `      base_url: ${esc(llmBase)}`,
    '  - name: vlm_review',
    '    model:',
    `      model_name: ${esc(vlmModel)}`,
    `      api_key: ${esc(vlmKey)}`,
    `      base_url: ${esc(vlmBase)}`,
    '    vlm_review_config:',
    '      enabled: true',
    '      provider: openai',
    `      vlm_model: ${esc(vlmModel)}`,
    `      vlm_api_key: ${esc(vlmKey)}`,
    `      vlm_base_url: ${esc(vlmBase)}`,
    '      render_dpi: 150',
    '      max_pages_to_analyze: 12',
    '      check_overflow: true',
    '      check_underfill: true',
    '      check_layout: false',
    '      min_fill_percentage: 0.85',
    '      max_blank_area: 0.15',
  ];
  return lines.join('\n');
}

export class ConfigPageViewProvider {
  public static currentPanel: ConfigPageViewProvider | undefined;
  private static readonly viewType = 'aiSocialScientistConfigPage';

  private readonly _panel: vscode.WebviewPanel;
  private readonly _extensionPath: string;
  private readonly _context: vscode.ExtensionContext;
  private readonly _envManager: EnvManager;
  private _disposables: vscode.Disposable[] = [];

  public static createOrShow(
    context: vscode.ExtensionContext,
    viewColumn: vscode.ViewColumn = vscode.ViewColumn.One
  ): void {
    if (ConfigPageViewProvider.currentPanel) {
      ConfigPageViewProvider.currentPanel._panel.reveal(viewColumn);
      return;
    }

    const panel = vscode.window.createWebviewPanel(
      ConfigPageViewProvider.viewType,
      localize('configPage.title'),
      viewColumn,
      {
        enableScripts: true,
        retainContextWhenHidden: true,
        localResourceRoots: [
          vscode.Uri.file(path.join(context.extensionPath, 'out', 'webview'))
        ]
      }
    );

    ConfigPageViewProvider.currentPanel = new ConfigPageViewProvider(panel, context);
  }

  private constructor(panel: vscode.WebviewPanel, context: vscode.ExtensionContext) {
    this._panel = panel;
    this._context = context;
    this._extensionPath = context.extensionPath;
    this._envManager = new EnvManager();

    this._panel.webview.html = this._getHtmlForWebview(this._panel.webview);

    this._panel.onDidDispose(() => this.dispose(), null, this._disposables);

    this._panel.webview.onDidReceiveMessage(
      async (message: { command: string; config?: Partial<ConfigValues>; llmType?: string }) => {
        switch (message.command) {
          case 'requestConfig':
            await this._sendInitialConfig();
            break;
          case 'saveConfig':
            await this._handleSaveConfig(message.config || {});
            break;
          case 'startBackend':
            await this._handleStartBackend(message.config || {});
            break;
          case 'validateConfig':
            await this._handleValidateConfig(message.config || {}, message.llmType);
            break;
          case 'validatePython':
            await this._handleValidatePython(message.config || {});
            break;
          case 'validateLiteratureSearch':
            await this._handleValidateLiteratureSearch(message.config || {});
            break;
          case 'closeConfigPage':
            this._panel.dispose();
            break;
          case 'openVscodeSettings':
            await vscode.commands.executeCommand('workbench.action.openSettings', '@aiSocialScientist');
            break;
          case 'openFolder':
            await vscode.commands.executeCommand('workbench.action.files.openFolder');
            break;
        }
      },
      null,
      this._disposables
    );
  }

  private async _sendInitialConfig(): Promise<void> {
    // Read from .env file instead of VSCode settings
    const envConfig = this._envManager.readEnv();

    const configValues: Partial<ConfigValues> = {
      llmApiKey: envConfig.llmApiKey || '',
      backendHost: envConfig.backendHost || '127.0.0.1',
      backendPort: envConfig.backendPort ?? 8001,
      pythonPath: envConfig.pythonPath || '',
      llmApiBase: envConfig.llmApiBase || 'https://cloud.infini-ai.com/maas/v1',
      llmModel: envConfig.llmModel || 'qwen3-next-80b-a3b-instruct',
      backendLogLevel: envConfig.backendLogLevel || 'info',
      coderLlmApiKey: envConfig.coderLlmApiKey || '',
      coderLlmApiBase: envConfig.coderLlmApiBase || '',
      coderLlmModel: envConfig.coderLlmModel || 'glm-4.7',
      nanoLlmApiKey: envConfig.nanoLlmApiKey || '',
      nanoLlmApiBase: envConfig.nanoLlmApiBase || '',
      nanoLlmModel: envConfig.nanoLlmModel || 'qwen3-next-80b-a3b-instruct',
      analysisLlmApiKey: envConfig.analysisLlmApiKey || '',
      analysisLlmApiBase: envConfig.analysisLlmApiBase || '',
      analysisLlmModel: envConfig.analysisLlmModel || 'glm-5',
      embeddingApiKey: envConfig.embeddingApiKey || '',
      embeddingApiBase: envConfig.embeddingApiBase || '',
      embeddingModel: envConfig.embeddingModel || 'bge-m3',
      embeddingDims: envConfig.embeddingDims ?? 1024,
      webSearchApiUrl: envConfig.webSearchApiUrl || '',
      webSearchApiToken: envConfig.webSearchApiToken || '',
      miroflowDefaultLlm: envConfig.miroflowDefaultLlm || 'qwen-3',
      miroflowDefaultAgent: envConfig.miroflowDefaultAgent || 'mirothinker_v1.5_keep5_max200',
      easypaperApiUrl: envConfig.easypaperApiUrl || '',
      easypaperLlmApiKey: envConfig.easypaperLlmApiKey || '',
      easypaperLlmModel: envConfig.easypaperLlmModel || 'qwen3-next-80b-a3b-instruct',
      easypaperVlmModel: envConfig.easypaperVlmModel || 'qwen3-vl-235b-a22b-thinking',
      easypaperVlmApiKey: envConfig.easypaperVlmApiKey || '',
      literatureSearchApiUrl: envConfig.literatureSearchApiUrl || 'http://localhost:8008/api/search',
      literatureSearchApiKey: envConfig.literatureSearchApiKey || '',
    };

    // 获取工作区信息
    const workspaceInfo: WorkspaceInfo = {
      hasWorkspace: !!(vscode.workspace.workspaceFolders && vscode.workspace.workspaceFolders.length > 0),
      workspacePath: vscode.workspace.workspaceFolders?.[0]?.uri.fsPath
    };

    this._panel.webview.postMessage({
      command: 'initialConfig',
      config: configValues
    });

    this._panel.webview.postMessage({
      command: 'workspaceInfo',
      workspaceInfo: workspaceInfo
    });
  }

  private async _handleSaveConfig(config: Partial<ConfigValues>): Promise<void> {
    try {
      await this._saveConfigInternal(config);
      this._panel.webview.postMessage({ command: 'saveResult', success: true });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this._panel.webview.postMessage({
        command: 'saveResult',
        success: false,
        error: message
      });
    }
  }

  private async _handleStartBackend(config: Partial<ConfigValues>): Promise<void> {
    try {
      // 确保配置已保存
      await this._saveConfigInternal(config);

      // 启动后端服务
      const success = await vscode.commands.executeCommand<boolean>('aiSocialScientist.startBackend');

      this._panel.webview.postMessage({
        command: 'startBackendResult',
        success: success !== false,
      });
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : String(err);
      this._panel.webview.postMessage({
        command: 'startBackendResult',
        success: false,
        error: message
      });
    }
  }

  private async _saveConfigInternal(config: Partial<ConfigValues>): Promise<void> {
    // 检查是否有工作区
    if (!vscode.workspace.workspaceFolders || vscode.workspace.workspaceFolders.length === 0) {
      throw new Error(localize('configPage.noWorkspace'));
    }

    // Write to .env file instead of VSCode settings
    this._envManager.writeEnv({
      llmApiKey: config.llmApiKey,
      backendHost: config.backendHost,
      backendPort: config.backendPort,
      pythonPath: config.pythonPath,
      llmApiBase: config.llmApiBase,
      llmModel: config.llmModel,
      backendLogLevel: config.backendLogLevel,
      coderLlmApiKey: config.coderLlmApiKey,
      coderLlmApiBase: config.coderLlmApiBase,
      coderLlmModel: config.coderLlmModel,
      nanoLlmApiKey: config.nanoLlmApiKey,
      nanoLlmApiBase: config.nanoLlmApiBase,
      nanoLlmModel: config.nanoLlmModel,
      analysisLlmApiKey: config.analysisLlmApiKey,
      analysisLlmApiBase: config.analysisLlmApiBase,
      analysisLlmModel: config.analysisLlmModel,
      embeddingApiKey: config.embeddingApiKey,
      embeddingApiBase: config.embeddingApiBase,
      embeddingModel: config.embeddingModel,
      embeddingDims: config.embeddingDims,
      webSearchApiUrl: config.webSearchApiUrl,
      webSearchApiToken: config.webSearchApiToken,
      miroflowDefaultLlm: config.miroflowDefaultLlm,
      miroflowDefaultAgent: config.miroflowDefaultAgent,
      easypaperApiUrl: config.easypaperApiUrl,
      easypaperLlmApiKey: config.easypaperLlmApiKey,
      easypaperLlmModel: config.easypaperLlmModel,
      easypaperVlmModel: config.easypaperVlmModel,
      easypaperVlmApiKey: config.easypaperVlmApiKey,
      literatureSearchApiUrl: config.literatureSearchApiUrl,
      literatureSearchApiKey: config.literatureSearchApiKey,
    });

    // If EasyPaper URL or any model field is set, write easypaper_agentsociety.yaml to workspace for EasyPaper to use
    const workspaceFolder = vscode.workspace.workspaceFolders?.[0];
    const hasEasyPaperConfig =
      (config.easypaperApiUrl ?? '').trim() !== '' ||
      (config.easypaperLlmModel ?? '').trim() !== '' ||
      (config.easypaperLlmApiKey ?? '').trim() !== '' ||
      (config.easypaperVlmModel ?? '').trim() !== '';
    if (workspaceFolder && hasEasyPaperConfig) {
      try {
        const yamlPath = path.join(workspaceFolder.uri.fsPath, 'easypaper_agentsociety.yaml');
        const yamlContent = buildEasyPaperYaml(config);
        fs.writeFileSync(yamlPath, yamlContent, 'utf8');
      } catch (e) {
        console.warn('Failed to write easypaper_agentsociety.yaml:', e);
      }
    }

    // 标记已完成初始配置
    await this._context.globalState.update('configPage.hasCompletedInitialSetup', true);
  }

  /**
   * 处理 LLM 配置验证请求
   */
  private async _handleValidateConfig(config: Partial<ConfigValues>, llmType: string = 'default'): Promise<void> {
    const validator = new LLMValidator();

    let apiKey: string = '';
    let apiBase: string = '';
    let model: string = '';
    let validationType: LLMType = LLMType.Chat;

    switch (llmType) {
      case 'coder':
        apiKey = config.coderLlmApiKey || '';
        apiBase = config.coderLlmApiBase || '';
        model = config.coderLlmModel || 'glm-4.7';
        break;
      case 'nano':
        apiKey = config.nanoLlmApiKey || '';
        apiBase = config.nanoLlmApiBase || '';
        model = config.nanoLlmModel || 'qwen3-next-80b-a3b-instruct';
        break;
      case 'analysis':
        apiKey = config.analysisLlmApiKey || '';
        apiBase = config.analysisLlmApiBase || '';
        model = config.analysisLlmModel || 'glm-5';
        break;
      case 'embedding':
        apiKey = config.embeddingApiKey || '';
        apiBase = config.embeddingApiBase || '';
        model = config.embeddingModel || 'bge-m3';
        validationType = LLMType.Embedding;
        break;
      case 'easypaperLlm':
        apiKey = config.easypaperLlmApiKey || '';
        apiBase = config.llmApiBase || 'https://cloud.infini-ai.com/maas/v1';
        model = config.easypaperLlmModel || 'qwen3-next-80b-a3b-instruct';
        break;
      case 'easypaperVlm':
        apiKey = config.easypaperVlmApiKey || '';
        apiBase = config.llmApiBase || 'https://cloud.infini-ai.com/ai.sap.com/v1';
        model = config.easypaperVlmModel || 'qwen3-vl-235b-a22b-thinking';
        break;
      default: // default LLM
        apiKey = config.llmApiKey || '';
        apiBase = config.llmApiBase || '';
        model = config.llmModel || 'qwen3-next-80b-a3b-instruct';
        break;
    }

    // 如果 coder/nano/embedding 的 API Key 或 Base URL 为空，使用默认 LLM 的配置
    if (!apiKey && llmType !== 'easypaperVlm') {
      apiKey = config.llmApiKey || '';
    }
    if (!apiBase) {
      apiBase = config.llmApiBase || '';
    }

    const result = await validator.validate({ apiKey, apiBase, model }, validationType);

    this._panel.webview.postMessage({
      command: 'validationResult',
      llmType,
      success: result.success,
      error: result.error || null,
    });
  }

  /**
   * 处理 Python 环境验证请求
   */
  private async _handleValidatePython(config: Partial<ConfigValues>): Promise<void> {
    const validator = new PythonValidator();
    const pythonPath = config.pythonPath || '';

    const result = await validator.validate({ pythonPath });

    this._panel.webview.postMessage({
      command: 'validationResult',
      llmType: 'python',
      success: result.success,
      error: result.error || null,
    });
  }

  /**
   * 处理文献检索 API 验证请求
   */
  private async _handleValidateLiteratureSearch(config: Partial<ConfigValues>): Promise<void> {
    const apiUrl = config.literatureSearchApiUrl || '';
    const apiKey = config.literatureSearchApiKey || '';

    try {
      // 从 API URL 中提取基础 URL（去掉 /api/search 部分）
      const baseUrl = apiUrl.replace(/\/api\/search\/?$/, '').replace(/\/$/, '');

      // 首先检查健康状态
      const healthUrl = `${baseUrl}/health`;
      const healthResponse = await fetch(healthUrl, { method: 'GET' });

      if (!healthResponse.ok) {
        this._panel.webview.postMessage({
          command: 'literatureValidationResult',
          success: false,
          error: `服务不可用: HTTP ${healthResponse.status}`,
        });
        return;
      }

      // 尝试获取数据源状态（验证认证）
      const statsUrl = `${baseUrl}/api/stats`;
      const statsResponse = await fetch(statsUrl, {
        method: 'GET',
        headers: apiKey ? { 'Authorization': `Bearer ${apiKey}` } : {},
      });

      if (statsResponse.status === 401 || statsResponse.status === 403) {
        // 需要 API Key 或 API Key 无效
        const errorMsg = apiKey ? 'API Key 无效' : '需要输入 API Key';
        this._panel.webview.postMessage({
          command: 'literatureValidationResult',
          success: false,
          error: errorMsg,
        });
        return;
      }

      if (!statsResponse.ok) {
        this._panel.webview.postMessage({
          command: 'literatureValidationResult',
          success: false,
          error: `验证失败: HTTP ${statsResponse.status}`,
        });
        return;
      }

      const statsData = await statsResponse.json() as { sources?: Record<string, unknown> };
      this._panel.webview.postMessage({
        command: 'literatureValidationResult',
        success: true,
        sources: statsData.sources,
      });
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : '未知错误';
      this._panel.webview.postMessage({
        command: 'literatureValidationResult',
        success: false,
        error: `连接失败: ${errorMessage}`,
      });
    }
  }

  private _getHtmlForWebview(webview: vscode.Webview): string {
    const scriptUri = webview.asWebviewUri(
      vscode.Uri.file(path.join(this._extensionPath, 'out', 'webview', 'configPage.js'))
    );

    return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src ${webview.cspSource} 'unsafe-inline'; script-src ${webview.cspSource} 'unsafe-eval' 'unsafe-inline'; connect-src *;">
  <title>${localize('configPage.title')}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: var(--vscode-font-family, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif);
      background: var(--vscode-editor-background);
      color: var(--vscode-editor-foreground);
      height: 100vh;
      overflow: auto;
    }
    #root { min-height: 100vh; }
  </style>
</head>
<body>
  <div id="root"></div>
  <script src="${scriptUri}"></script>
</body>
</html>`;
  }

  public dispose(): void {
    ConfigPageViewProvider.currentPanel = undefined;
    this._envManager.dispose();
    while (this._disposables.length) {
      const d = this._disposables.pop();
      if (d) { d.dispose(); }
    }
  }
}
